### ISSUE TITLE
Find and install theme

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-paparazzme#1]
URL: paparazzme.editllc.com/wp-admin

I already shared the creds with you via lastpass.

Find a free WP theme with a large video or picture background 

due: 10-16-15    3p

**Comment by rcsargent** [comment]
Punch me out for commenting... 
- https://www.elegantthemes.com/blog/tips-tricks/video-backgrounds-for-wordpress-when-and-how-to-add-them-to-your-website
- Sorry not free but, crazy ratings and downloads - http://themeforest.net/item/bridge-creative-multipurpose-wordpress-theme/7315054

**Comment by rodneystrong** [comment]
I will punch out anyone who punches out @rcsargent for commenting.

**Comment by purplyrocky** [comment]
http://paparazzme.editllc.com/
