### ISSUE TITLE
Design the site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-paparazzme#4]
Use the theme.works theme we just got to design a theme. 

paparazzme.editllc.com
I shared the creds with you via lastpass

Two goals for the site:
- get freelance photographers/filmers to sign up and be available for work
- get customers to request a photographer/filmer and pay on the site

I'm already using a theme with pagebuilder, but I want you to try out theme.works. Feel free to continue with the aesthetic I have or scrap it completely, but be sure to note the different functional elements I have on the site. 

Images from the client can be found on our google drive

due:
11-7-15     4p

**Comment by rodneystrong** [comment]
Also, for the video background at the top, think of a fallback for that on mobile devices. 
I know that the theme automatically hides the video when you view it on a phone (you ARE viewing this on a phone as develop it right?) 

Client gave us a bunch of images to use so see if there's a built-in wordpress option to change the video to an image when on a mobile device. 

If there is no built-in option, then you're gonna have to code the CSS yourself.

**Comment by jperez4509** [comment]
@rodneystrong Done. It should also be fully responsive.

**Comment by jperez4509** [comment]
Oh and yes. I checked it on my iphone 6 and ipad.
