### ISSUE TITLE
Add another parallax section

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-paparazzme#5]
Use one of the pictures of the girls as the background, and be sure to remove it from the carousel. 

Get creative; use a quote you think is relevant as content for the section or don't; think of what the client would want there. 

due:
11-9-15    4p

**Comment by jperez4509** [comment]
I need to extend this deadline to tomorrow. It should be done by tomorrow at 4pm.

**Comment by jperez4509** [comment]
Done.
