### ISSUE TITLE
Content from Client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-paparazzme#6]
he took pictures of his notes..

![20151110_160909-1](https://cloud.githubusercontent.com/assets/539962/11103818/b31682ca-8879-11e5-9d56-94da5aded72c.jpg)
![20151110_161154-2](https://cloud.githubusercontent.com/assets/539962/11103819/b318da3e-8879-11e5-9d76-778689eb8434.jpg)
![20151110_161259-1](https://cloud.githubusercontent.com/assets/539962/11103820/b3193a74-8879-11e5-8086-0d8ec80162d5.jpg)
![20151110_161329-1](https://cloud.githubusercontent.com/assets/539962/11103821/b31bf05c-8879-11e5-934f-21355e4bbff0.jpg)
![20151110_161602-1](https://cloud.githubusercontent.com/assets/539962/11103822/b31dd782-8879-11e5-863e-2fb5b3bbe137.jpg)

due:
11-12-15   6p

**Comment by rodneystrong** [comment]
More content from client: 

![screenshot_2015-11-11-10-34-21](https://cloud.githubusercontent.com/assets/539962/11105341/13929d9c-8883-11e5-85c0-b459b1897fb6.png)

**Comment by jperez4509** [comment]
This has been completed. The only thing I need to help on is created the form that works with paypal

**Comment by rodneystrong** [comment]
perfect, thank you sir.
