### ISSUE TITLE
content from client #2

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-paparazzme#7]
![20151202_095127](https://cloud.githubusercontent.com/assets/539962/11576488/d337ab16-99cb-11e5-923d-f4a9c30f4b04.jpg)

The primary audience is people using the Reality Show option or, DOCUMENTARIES, PROFESSIONAL PICTURES, Paparazzi Effect, DAY in the life, Music Video, Short film Movie. That's primary then under all these cool options you will see Wedding Photography,  birthday Parties, Bachelor Parties, Kids Parties, and events.
Each category that you see has and link to it. Basically once you click on one that goes into another page. Showing price and what u get at that price..
I will send u pricing later today.

due:
12-4-15  4p

**Comment by jperez4509** [comment]
Is this a new page? or a new section on the home page? I dont really understand the instructions.

**Comment by rodneystrong** [comment]
These will go under "Our Services" on the home page: 
DOCUMENTARIES, PROFESSIONAL PICTURES, Paparazzi Effect, DAY in the life, Music Video, Short film Movie

Each will have it's own icon and be linked to a new self-titled page.

**Comment by jperez4509** [comment]
Done.
