### ISSUE TITLE
Changes to the site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-paparazzme#8]
Wherever it says "paparazzi" on the site, change it to "papparazme". They spell papparazme with two "p's" and one "z". Don't know why. 

due:
12-21-15  4p

updated due:
12-26-15  3p

**Comment by rampage1213** [comment]
Done

**Comment by rodneystrong** [comment]
Unfortunately there are still instances of the word "paparazzi". **In the nav menu under "Services" you'll find one instance**, and here's a screenshot of another instance: 

<img width="686" alt="screen shot 2015-12-23 at 5 15 18 pm" src="https://cloud.githubusercontent.com/assets/539962/11987698/d3cbeb32-a998-11e5-9e06-715f63114033.png">

Please go back and change these to be "paparazzme". 

updated due:
12-26-15    3p

**Comment by rodneystrong** [comment]
Quick note, these are just the instances that I was able to find, but that doesn't mean there aren't other instances of the incorrect spelling. 

Please be comprehensive in your search. You can save time by using "cmd + f" to search for the incorrect spelling of "paparazzi".

**Comment by rampage1213** [comment]
Done!

**Comment by rodneystrong** [comment]
Good stuff dude.
