### ISSUE TITLE
Update "Paparazzme effect" page

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-paparazzme#9]
http://paparazzme.editllc.com/paparazzi-affect/

>The second have of this Paragraph where it says what kind of questions you want the papparazme team to ask you while snapping photos. Implement that some where along with, what kind of car you will be getting out of?, how many people will you be with you?, where will we be snapping pictures of you?

![20151214_110230](https://cloud.githubusercontent.com/assets/539962/11912326/a1ba9fbc-a5ec-11e5-8b28-1969991a9db7.jpg)

Also add this to that page: 

![20151214_110214](https://cloud.githubusercontent.com/assets/539962/11912335/d1d36896-a5ec-11e5-872e-7eed93259d4e.jpg)

I've shared the creds with you via lastpass

due:
12-21-15   4p

**Comment by rampage1213** [comment]
Done!

**Comment by rodneystrong** [comment]
Nicely done. I like how you laid it out.
